### ISSUE TITLE
The Chatwoot SuperAdmin UI is missing important fields in this Railway template.

### ISSUE THREAD

**Issue by pryley** [railwayapp-templates/chatwoot#2]
Something is wrong with this template.

After installing Chatwoot on Railway, I went to the SuperAdmin UI to enable the ip_lookup feature, but the "Limits" and "All features" fields are missing.

This is what the "SuperAdmin UI looks like after installing with the template: 

<img width="1178" alt="image" src="https://github.com/railwayapp-templates/chatwoot/assets/134939/c2533563-8604-4363-a5dd-23df9fc7c953">

<img width="1177" alt="image" src="https://github.com/railwayapp-templates/chatwoot/assets/134939/15fe204a-7e6e-4d49-b335-81e423b8bac4">

But this is what it should look like:

<img width="1178" alt="image" src="https://github.com/railwayapp-templates/chatwoot/assets/134939/7ddc1baf-3353-4479-9c13-f3e187b17040">

<img width="1178" alt="image" src="https://github.com/railwayapp-templates/chatwoot/assets/134939/9d656b91-c139-4f64-90cd-7fcaf9a007dc">

**Comment by brody192** [comment]
That could be enterprise features, by default the template deploys the community edition

**Comment by pryley** [comment]
No, the first two screenshots are from the Railway template, the last two screenshots are from a local installation of the community edition from GitHub (default settings).

**Comment by brody192** [comment]
The template deploys from a docker image, perhaps there are some discrepancies there?

**Comment by pryley** [comment]
Maybe there is an issue with the docker image. 

Directions I followed to enable IP detection is here: https://www.chatwoot.com/docs/self-hosted/configuration/enable-ip-logging/

Directions I followed to install locally on macOS here: https://www.chatwoot.com/docs/contributing-guide/environment-setup/mac-os/

**Comment by brody192** [comment]
have you added that environment variable to the service variables?

side note, this template uses the official images - https://github.com/railwayapp-templates/chatwoot/blob/main/Dockerfile.Community#L2

**Comment by pryley** [comment]
> Have you added that environment variable to the service variables of your chatwoot service?
Yes.

**Comment by brody192** [comment]
Can you run the docker images locally? That's how the template is deployed

**Comment by pryley** [comment]
I ran the docker image locally and it worked as expected. Here is what I did:

## Run Chatwoot in Docker on macOS

1. Download and install the latest version of [Docker Desktop](https://www.docker.com/products/docker-desktop/)
2. Add Docker CLI to PATH
```sh
export PATH="$HOME/.docker/bin:$PATH"
```
3. Sign in to Docker Desktop with Github credentials
4. Login to Docker in the terminal
```
docker login
```
5. Clone the Chatwoot repo
```
git clone https://github.com/chatwoot/chatwoot.git .
```
6. Create the `.env` file
```
cp .env.example .env
``` 
7. Edit `.env` and set the Redis and Postgres password
```env
REDIS_PASSWORD=1234
POSTGRES_PASSWORD=1234
```
8. Use the `docker-compose.production.yaml` file
```
mv docker-compose.yaml docker-compose.development.yaml
cp docker-compose.production.yaml docker-compose.yaml
```
9. Edit `docker-compose.yaml`, set the Postgress password, and update the volume paths (because we are using macOS)
```yaml
services:
  base: &base
    volumes:
      - /tmp/chatwoot/data/storage:/app/storage

  postgres:
    volumes:
      - /tmp/chatwoot/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234

  redis:
    volumes:
      - /tmp/chatwoot/data/redis:/data
```
10. Build the Docker images
```
docker-compose build
```
11. Install Chatwoot
```
docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
```
12. Run Chatwoot
```
docker-compose up
```

## Result

<img width="1049" alt="image" src="https://github.com/railwayapp-templates/chatwoot/assets/134939/02143923-2cb1-4e5c-bf98-fd7e2d6abdb1">

<img width="1049" alt="image" src="https://github.com/railwayapp-templates/chatwoot/assets/134939/cb260550-0159-4442-86ec-2f31ea621ccd">

**Comment by brody192** [comment]
The production docker-compose file deploys the enterprise image - [docker-compose.production.yaml#L5](https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml#L5)
Running the local environment setup of Chatwoot likely does the same thing.

As mentioned in my first reply, the template deploys the community edition by default - [ghcr.io/railwayapp-templates/chatwoot:Community](https://github.com/railwayapp-templates/chatwoot/blob/main/Dockerfile.Community#L2)

Swapping to the enterprise template image on Railway is as easy as changing the image tag from `Community` to `Enterprise`
This is mentioned in the [template overview](https://railway.app/template/chatwoot) and in the [forum post](https://community.railway.app/templates/chatwoot-c520cf8d#p-1).

I went ahead and deployed Chatwoot and changed the image tag to `Enterprise` now my super admin page looks the same as the screenshots you have just shown.
