### ISSUE TITLE
What is the best way to upgrade chatwoot?

### ISSUE THREAD

**Issue by sangdth** [railwayapp-templates/chatwoot#3]
I saw the message `An update 3.6.0 for Chatwoot is available.`, just wonder what is the best way to upgrade to newer version if I'm using this template? Wait for this template update?

**Comment by brody192** [comment]
my bad, I will run the action soon

**Comment by brody192** [comment]
action has been ran, you can now redeploy your chatwoot service

**Comment by sangdth** [comment]
Thanks @brody192, you are awesome!
